const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
  LevelFormat, PageBreak
} = require('docx');
const fs = require('fs');

const C = {
  primary:"1A3A6B", secondary:"1D6A3A", accent:"B84000",
  h1bg:"1A3A6B", h2bg:"E8EEF7", codeBg:"F2F2F2", exBg:"EAF4EA",
  corBg:"FFF8EE", defBg:"EEF2FF", noteBg:"FFF3CD",
  text:"1A1A1A", white:"FFFFFF",
};
const bd=(style,color="BBBBBB")=>({style:BorderStyle.SINGLE,size:4,color});
const borders=(col="CCCCCC")=>({top:bd("SINGLE",col),bottom:bd("SINGLE",col),left:bd("SINGLE",col),right:bd("SINGLE",col)});
const sp=(b=0,a=0)=>({spacing:{before:b,after:a}});
const br=()=>new Paragraph({children:[new PageBreak()]});

function h1(text){return new Paragraph({heading:HeadingLevel.HEADING_1,children:[new TextRun({text,color:C.white,bold:true,size:32,font:"Arial"})],shading:{fill:C.h1bg,type:ShadingType.CLEAR},...sp(320,160)});}
function h2(text){return new Paragraph({heading:HeadingLevel.HEADING_2,children:[new TextRun({text,color:C.primary,bold:true,size:26,font:"Arial"})],shading:{fill:C.h2bg,type:ShadingType.CLEAR},...sp(220,100)});}
function h3(text){return new Paragraph({heading:HeadingLevel.HEADING_3,children:[new TextRun({text,bold:true,size:23,color:C.primary,font:"Arial"})],...sp(180,80),border:{bottom:{style:BorderStyle.SINGLE,size:2,color:"CCCCCC"}}});}
function p(text,opts={}){return new Paragraph({children:[new TextRun({text,size:22,font:"Arial",color:C.text,...opts})],...sp(80,80)});}
function bul(text,level=0){return new Paragraph({numbering:{reference:"bullets",level},children:[new TextRun({text,size:22,font:"Arial",color:C.text})],...sp(50,50)});}
function spc(n=1){return Array.from({length:n},()=>new Paragraph({children:[new TextRun("")],  ...sp(30,30)}));}

function colorBox(title,lines,bg,borderCol,titleColor){
  return new Table({width:{size:9200,type:WidthType.DXA},rows:[new TableRow({children:[new TableCell({borders:borders(borderCol),shading:{fill:bg,type:ShadingType.CLEAR},margins:{top:120,bottom:120,left:200,right:200},width:{size:9200,type:WidthType.DXA},children:[new Paragraph({children:[new TextRun({text:title,bold:true,size:23,font:"Arial",color:titleColor})],...sp(60,100)}),...lines.map(l=>new Paragraph({children:[new TextRun({text:l,size:21,font:"Arial",color:C.text})],...sp(50,50)}))]})]})]});
}
function defBox(title,lines){return colorBox(title,lines,C.defBg,"90A8E8",C.primary);}
function codeBox(lines){return new Table({width:{size:9200,type:WidthType.DXA},rows:[new TableRow({children:[new TableCell({borders:borders("90A8E8"),shading:{fill:C.codeBg,type:ShadingType.CLEAR},margins:{top:120,bottom:120,left:200,right:200},width:{size:9200,type:WidthType.DXA},children:lines.map(l=>new Paragraph({children:[new TextRun({text:l,size:19,font:"Courier New",color:"1A237E"})],...sp(25,25)}))})]})]});}
function exoBox(title,lines){return colorBox("✏️  "+title,lines,C.exBg,"5DAA6A",C.secondary);}
function corBox(title,lines){return new Table({width:{size:9200,type:WidthType.DXA},rows:[new TableRow({children:[new TableCell({borders:borders("E6A840"),shading:{fill:C.corBg,type:ShadingType.CLEAR},margins:{top:120,bottom:120,left:200,right:200},width:{size:9200,type:WidthType.DXA},children:[new Paragraph({children:[new TextRun({text:"✅  "+title,bold:true,size:23,font:"Arial",color:C.accent})],...sp(60,100)}),...lines.map(l=>new Paragraph({children:[new TextRun({text:l,size:20,font:"Courier New",color:"37474F"})],...sp(30,30)}))]})]})]})}
function noteBox(text){return new Table({width:{size:9200,type:WidthType.DXA},rows:[new TableRow({children:[new TableCell({borders:borders("F0C040"),shading:{fill:C.noteBg,type:ShadingType.CLEAR},margins:{top:100,bottom:100,left:200,right:200},width:{size:9200,type:WidthType.DXA},children:[new Paragraph({children:[new TextRun({text:"💡  "+text,size:21,font:"Arial",color:"7A4800"})],...sp(40,40)})]})]})]});}

function table2col(header1,header2,rows){
  const hborder=borders("1A3A6B"),cborder=borders("CCCCCC"),W1=4500,W2=4700;
  return new Table({width:{size:9200,type:WidthType.DXA},columnWidths:[W1,W2],rows:[
    new TableRow({children:[
      new TableCell({borders:hborder,shading:{fill:C.primary,type:ShadingType.CLEAR},width:{size:W1,type:WidthType.DXA},margins:{top:80,bottom:80,left:120,right:120},children:[new Paragraph({children:[new TextRun({text:header1,bold:true,color:C.white,font:"Arial",size:21})]})]}),
      new TableCell({borders:hborder,shading:{fill:C.primary,type:ShadingType.CLEAR},width:{size:W2,type:WidthType.DXA},margins:{top:80,bottom:80,left:120,right:120},children:[new Paragraph({children:[new TextRun({text:header2,bold:true,color:C.white,font:"Arial",size:21})]})]}),
    ]}),
    ...rows.map(([c1,c2])=>new TableRow({children:[
      new TableCell({borders:cborder,shading:{fill:C.h2bg,type:ShadingType.CLEAR},width:{size:W1,type:WidthType.DXA},margins:{top:80,bottom:80,left:120,right:120},children:[new Paragraph({children:[new TextRun({text:c1,bold:true,font:"Arial",size:20,color:C.primary})]})]}),
      new TableCell({borders:cborder,width:{size:W2,type:WidthType.DXA},margins:{top:80,bottom:80,left:120,right:120},children:[new Paragraph({children:[new TextRun({text:c2,font:"Arial",size:20,color:C.text})]})]}),
    ]}))
  ]});
}

const children = [
  // PAGE DE TITRE
  new Paragraph({children:[new TextRun({text:"RÉSUMÉ DÉTAILLÉ",bold:true,size:52,font:"Arial",color:C.white})],alignment:AlignmentType.CENTER,shading:{fill:C.primary,type:ShadingType.CLEAR},...sp(0,60)}),
  new Paragraph({children:[new TextRun({text:"Chapitre 2 : Les Systèmes Experts",bold:true,size:38,font:"Arial",color:C.white})],alignment:AlignmentType.CENTER,shading:{fill:C.primary,type:ShadingType.CLEAR},...sp(0,60)}),
  new Paragraph({children:[new TextRun({text:"Intelligence Artificielle — GLSI2 — ISTIC 2025/2026",size:22,font:"Arial",color:"BBCCEE"})],alignment:AlignmentType.CENTER,shading:{fill:C.primary,type:ShadingType.CLEAR},...sp(0,200)}),
  new Paragraph({children:[new TextRun({text:"Dr. Mariem Farhat",size:22,font:"Arial",color:C.text,italics:true})],alignment:AlignmentType.CENTER,...sp(120,40)}),
  new Paragraph({children:[new TextRun({text:"Contenu : Théorie · Exemples · Exercices corrigés · Exercice général",size:20,font:"Arial",color:"555555"})],alignment:AlignmentType.CENTER,border:{bottom:{style:BorderStyle.SINGLE,size:6,color:C.primary}},...sp(0,80)}),
  ...spc(2),

  // TABLE DES MATIÈRES
  h2("📋  Table des matières"),
  p("Partie 1  —  Définition et domaines d'application"),
  p("Partie 2  —  Composants d'un système expert"),
  p("Partie 3  —  Fonctionnement et moteur d'inférence"),
  p("Partie 4  —  Le chaînage avant"),
  p("Partie 5  —  Le chaînage arrière"),
  p("Partie 6  —  Le backtracking"),
  p("Partie 7  —  L'arbre ET/OU"),
  p("Partie 8  —  Avantages, limites et systèmes modernes"),
  p("Exercice Général  —  Synthèse complète du chapitre"),
  br(),

  // PARTIE 1
  h1("PARTIE 1 — Définition et Domaines d'Application"),
  h2("1.1  Définition"),
  defBox("Définition officielle",[
    "Un système expert est un programme informatique qui imite le raisonnement",
    "d'un expert humain dans un domaine précis (médecine, diagnostic, finance...).",
    "Il utilise des connaissances et des règles logiques pour prendre des décisions.",
  ]),
  ...spc(1),
  p("Trois caractéristiques fondamentales :"),
  bul("Spécialisation : conçu pour UN seul domaine précis."),
  bul("Raisonnement : applique des règles logiques SI … ALORS …"),
  bul("Explication : peut justifier ses conclusions (traçabilité du raisonnement)."),
  ...spc(1),
  h2("1.2  Exemple historique : MYCIN (1976)"),
  p("Premier système expert médical majeur. Développé à Stanford pour diagnostiquer les infections bactériennes du sang."),
  noteBox("Performance : MYCIN a obtenu 65% de diagnostics corrects, contre 42% à 62% pour les médecins humains."),
  ...spc(1),
  codeBox([
    "Règle MYCIN :",
    "SI  l'infection est à Gram positif",
    "ET  le germe est un staphylocoque",
    "ALORS  certitude = 0.7 qu'il s'agisse d'un Staphylocoque aureus",
    "→ Le système donne un DEGRÉ DE CONFIANCE, pas un simple OUI/NON.",
  ]),
  ...spc(1),
  h2("1.3  Domaines d'application"),
  table2col("Domaine","Application concrète",[
    ["Médecine","Diagnostic de maladies, recommandation de traitements (MYCIN)"],
    ["Maintenance","Diagnostic de pannes automobiles ou industrielles"],
    ["Finance","Aide à la décision, détection de fraudes"],
    ["Éducation","Tutoriels intelligents adaptés au niveau de l'apprenant"],
    ["Informatique","Configuration de systèmes, débogage de logiciels"],
    ["Droit","Analyse juridique, conseil sur des cas légaux"],
  ]),
  ...spc(2),
  h2("📌  Exemple développé — Partie 1"),
  codeBox([
    "Système expert — Panne de voiture :",
    "  R1 : SI moteur_ne_démarre_pas ET batterie_faible  ALORS problème = batterie",
    "  R2 : SI moteur_ne_démarre_pas ET batterie_ok ET démarreur_silencieux",
    "       ALORS problème = démarreur",
    "  R3 : SI moteur_démarre ET fumée_noire             ALORS problème = injection",
    "",
    "Faits du cas : moteur_ne_démarre_pas=vrai, batterie_faible=vrai",
    "Conclusion   : problème = batterie  (via R1)",
  ]),
  ...spc(2),
  exoBox("Exercice 1 — Définitions et domaines",[
    "1. Donnez une définition d'un système expert en vos propres mots.",
    "2. Citez 3 domaines d'application et un exemple de règle pour chacun.",
    "3. Qu'est-ce qui distingue un SE d'un programme classique ?",
    "4. Expliquez en quoi MYCIN était innovant pour son époque.",
  ]),
  ...spc(1),
  corBox("Correction Exercice 1",[
    "1. Un SE est un logiciel qui reproduit le raisonnement d'un spécialiste humain",
    "   grâce à une base de règles et un moteur d'inférence automatique.",
    "",
    "2. Trois domaines :",
    "   • Médecine : SI fièvre ET toux ALORS grippe possible",
    "   • Finance  : SI solde_négatif ET revenus_insuffisants ALORS refus_crédit",
    "   • Auto     : SI voyant_rouge ET niveau_huile_bas ALORS vidange_urgente",
    "",
    "3. Un programme classique suit des instructions fixes. Un SE raisonne",
    "   dynamiquement à partir d'une base de connaissances modifiable.",
    "",
    "4. MYCIN : surpassait les experts humains (65% vs 62%), gérait l'incertitude",
    "   avec des facteurs de certitude (-1 à 1), et expliquait ses conclusions.",
  ]),
  br(),

  // PARTIE 2
  h1("PARTIE 2 — Composants d'un Système Expert"),
  h2("2.1  Vue d'ensemble"),
  table2col("Composant","Rôle",[
    ["Base de connaissances","Stocke les règles (SI…ALORS) et les faits généraux du domaine"],
    ["Base de faits","Contient les données spécifiques au cas en cours de traitement"],
    ["Moteur d'inférence","Applique les règles pour déduire de nouvelles conclusions"],
    ["Interface utilisateur","Permet de saisir les données et de recevoir les réponses"],
  ]),
  ...spc(1),
  h2("2.2  La Base de Connaissances"),
  bul("Faits : informations générales et permanentes sur le domaine."),
  bul("Règles : formules logiques de la forme SI [conditions] ALORS [conclusion]."),
  codeBox([
    "Exemple — Base de connaissances médicale :",
    "  R1 : SI fièvre ET toux                 ALORS grippe_possible",
    "  R2 : SI fièvre ET toux ET courbatures  ALORS grippe_probable",
    "  R3 : SI grippe_probable ET âge > 65    ALORS hospitalisation_recommandée",
    "  R4 : SI infection_bactérienne           ALORS antibiotique_nécessaire",
  ]),
  ...spc(1),
  h2("2.3  La Base de Faits"),
  p("Dynamique et propre à chaque consultation. S'enrichit au fil du raisonnement."),
  codeBox([
    "Faits initiaux (patient) : fièvre=vrai, toux=vrai, fatigue=vrai, age=70",
    "Faits déduits :",
    "  → grippe_possible           (déduit par R1)",
    "  → grippe_probable           (déduit par R2)",
    "  → hospitalisation_recommandée (déduit par R3)",
  ]),
  ...spc(1),
  h2("2.4  Le Moteur d'Inférence"),
  bul("Chaînage avant : part des faits → cherche les conclusions possibles."),
  bul("Chaînage arrière : part d'une conclusion → vérifie si les faits la justifient."),
  ...spc(1),
  h2("📌  Exemple développé — Partie 2"),
  codeBox([
    "Système 'Animaux' :",
    "  R1 : SI animal_vole ET pond_oeufs         ALORS oiseau",
    "  R2 : SI oiseau ET poids < 10g             ALORS colibri",
    "  R3 : SI oiseau ET ne_vole_pas             ALORS pingouin",
    "",
    "Faits : animal_vole=vrai, pond_oeufs=vrai, poids=8g",
    "  Étape 1 : R1 → ajoute 'oiseau'",
    "  Étape 2 : R2 (oiseau + 8g < 10g) → ajoute 'colibri'",
    "  Étape 3 : R3 non applicable (l'animal vole)",
    "  Conclusion : L'animal est un colibri.",
  ]),
  ...spc(2),
  exoBox("Exercice 2 — Composants",[
    "1. Quelles sont les 4 composantes d'un SE ? Définissez chacune.",
    "2. Quelle est la différence entre base de connaissances et base de faits ?",
    "3. Donnez un exemple de SE en finance avec :",
    "   a) 3 règles dans la base de connaissances",
    "   b) Une base de faits pour un client",
    "   c) La conclusion que le moteur devrait produire",
  ]),
  ...spc(1),
  corBox("Correction Exercice 2",[
    "1. Les 4 composantes :",
    "   • Base de connaissances : règles + faits généraux du domaine",
    "   • Base de faits : données spécifiques au cas en cours",
    "   • Moteur d'inférence : applique les règles pour déduire de nouvelles infos",
    "   • Interface utilisateur : saisie des données + affichage du résultat",
    "",
    "2. Base de connaissances = permanente, valable pour tous les cas.",
    "   Base de faits = temporaire, propre à chaque session.",
    "",
    "3. Système financier :",
    "   R1 : SI revenu > 3000 ET CDI=vrai  ALORS solvable",
    "   R2 : SI solvable ET prêt < 50000   ALORS accord_prêt",
    "   R3 : SI incidents_bancaires > 2    ALORS refus_prêt",
    "   Faits client : revenu=3500, CDI=vrai, prêt=20000, incidents=0",
    "   Conclusion : R1→solvable ; R2→accord_prêt accordé.",
  ]),
  br(),

  // PARTIE 3
  h1("PARTIE 3 — Fonctionnement du Moteur d'Inférence"),
  h2("3.1  Principe général"),
  bul("Étape 1 : L'utilisateur fournit les informations (les faits initiaux)."),
  bul("Étape 2 : Le moteur d'inférence applique les règles de la base de connaissances."),
  bul("Étape 3 : Le système déduit une conclusion ou propose une solution."),
  codeBox([
    "Exemple : Entrée = fièvre + toux",
    "Règle   : SI fièvre ET toux ALORS grippe_possible",
    "Sortie  : 'Vous pourriez avoir une grippe.'",
  ]),
  ...spc(1),
  h2("3.2  Mécanisme de filtrage"),
  p("Le moteur vérifie si les prémisses d'une règle sont satisfaites dans la base de faits."),
  codeBox([
    "Base des règles :",
    "  R1 : SI animal_vole ET poids < 10g   ALORS colibri",
    "  R2 : SI animal_vole ET pond_des_oeufs ALORS oiseau",
    "Base des faits : animal_vole=vrai, pond_des_oeufs=vrai, poids=8g",
    "",
    "Filtrage :",
    "  R1 : [animal_vole✓, poids=8g<10g✓] → APPLICABLE",
    "  R2 : [animal_vole✓, pond_des_oeufs✓] → APPLICABLE",
    "→ Les deux sont dans le Conflict Set. Le moteur en choisit une.",
  ]),
  noteBox("Le moteur regarde dans la base de faits si les prémisses d'une règle sont vraies avant de l'appliquer."),
  ...spc(2),
  h2("📌  Exemple développé — Système Pâtisserie"),
  codeBox([
    "Règles :",
    "  R1 : SI farine ET beurre ET oeufs ET sel  ALORS pâte",
    "  R2 : SI pommes ET sucre                   ALORS pommes_sucrées",
    "  R3 : SI pommes_sucrées ET pâte            ALORS tarte_aux_pommes",
    "  R4 : SI abricots ET pâte                  ALORS tarte_aux_abricots",
    "  R5 : SI poires ET pâte                    ALORS tarte_aux_poires",
    "  R6 : SI cerises ET pâte                   ALORS tarte_aux_cerises",
    "Faits initiaux : pommes, poires, abricots, farine, beurre, oeufs, sucre, sel",
    "",
    "Tour 1 : R1 → ajoute pâte",
    "Tour 2 : R2 → ajoute pommes_sucrées",
    "Tour 3 : R3 → tarte_aux_pommes | R4 → tarte_aux_abricots | R5 → tarte_aux_poires",
    "Tour 4 : R6 NON applicable (cerises absente)",
    "Résultat : 3 tartes réalisables. Tarte cerises impossible.",
  ]),
  ...spc(2),
  exoBox("Exercice 3 — Fonctionnement",[
    "Système 'Véhicules' :",
    "  R1 : SI moteur ET roues ET carrosserie   ALORS véhicule",
    "  R2 : SI véhicule ET 2_roues             ALORS deux_roues",
    "  R3 : SI véhicule ET 4_roues             ALORS quatre_roues",
    "  R4 : SI deux_roues ET moteur_électrique  ALORS scooter_électrique",
    "  R5 : SI quatre_roues ET moteur_essence   ALORS voiture_essence",
    "  R6 : SI quatre_roues ET moteur_électrique ALORS voiture_électrique",
    "Faits : moteur, roues, carrosserie, 4_roues, moteur_électrique",
    "",
    "1. Appliquez le chaînage avant étape par étape.",
    "2. Quelles règles sont applicables à chaque tour ?",
    "3. Quelle est la conclusion finale ?",
    "4. Quelle règle ne peut jamais être déclenchée ? Pourquoi ?",
  ]),
  ...spc(1),
  corBox("Correction Exercice 3",[
    "Tour 1 : R1 [moteur✓,roues✓,carrosserie✓] → ajoute 'véhicule'",
    "Tour 2 : R3 [véhicule✓,4_roues✓] → ajoute 'quatre_roues'",
    "         (R2 : 2_roues absent ✗)",
    "Tour 3 : R6 [quatre_roues✓,moteur_électrique✓] → ajoute 'voiture_électrique'",
    "         (R5 : moteur_essence absent ✗)",
    "Tour 4 : Aucune règle applicable → arrêt.",
    "",
    "3. Conclusion : voiture_électrique",
    "4. R4 (scooter_élec) : 2_roues absent. R5 (voiture_essence) : moteur_essence absent.",
  ]),
  br(),

  // PARTIE 4
  h1("PARTIE 4 — Le Chaînage Avant"),
  defBox("Chaînage avant — Définition",[
    "Mécanisme de raisonnement guidé par les données (faits).",
    "On part de la base de faits initiale et on cherche toutes les conclusions.",
    "Direction : Faits  →  Conclusions",
  ]),
  ...spc(1),
  h2("4.2  Algorithme"),
  bul("Étape 1 (Filtrage) : détecter toutes les règles dont les prémisses sont vérifiées."),
  bul("Étape 2 (Sélection) : choisir une règle parmi celles applicables."),
  bul("Étape 3 (Application) : ajouter la conclusion dans la base de faits, désactiver la règle."),
  bul("Étape 4 (Répétition) : retourner à l'étape 1 jusqu'à saturation."),
  codeBox([
    "Pseudo-code :",
    "TANT QUE il_existe_une_règle_applicable :",
    "    règle = sélectionner_règle(ensemble_applicable)",
    "    base_de_faits.ajouter(conclusion_de_règle)",
    "    base_de_règles.désactiver(règle)",
    "FIN",
    "AFFICHER base_de_faits",
  ]),
  ...spc(1),
  h2("📌  Exemple — Système e-mails"),
  codeBox([
    "R1 : SI expéditeur_inconnu ET contient_lien    ALORS suspect",
    "R2 : SI suspect ET demande_mot_de_passe         ALORS phishing",
    "R3 : SI phishing                                ALORS déplacer_spam",
    "Faits : expéditeur_inconnu=vrai, contient_lien=vrai, demande_mot_de_passe=vrai",
    "",
    "Tour 1 : R1 → suspect",
    "Tour 2 : R2 → phishing",
    "Tour 3 : R3 → déplacer_spam",
    "Conclusion : L'e-mail est un phishing → déplacé dans les spams.",
  ]),
  ...spc(2),
  exoBox("Exercice 4 — Chaînage avant",[
    "Système 'Plantes' :",
    "  R1 : SI eau ET lumière ET terre        ALORS plante_vivante",
    "  R2 : SI plante_vivante ET fleurs       ALORS plante_fleurie",
    "  R3 : SI plante_fleurie ET odeur        ALORS plante_parfumée",
    "  R4 : SI plante_vivante ET fruits       ALORS plante_fruitière",
    "  R5 : SI plante_fruitière ET comestible  ALORS plante_alimentaire",
    "  R6 : SI plante_parfumée ET rare         ALORS plante_précieuse",
    "Faits : eau, lumière, terre, fleurs, odeur, fruits, comestible",
    "",
    "1. Appliquez le chaînage avant étape par étape.",
    "2. Listez toutes les règles déclenchées dans l'ordre.",
    "3. Donnez la base de faits finale.",
    "4. Quelle règle ne se déclenche pas ? Pourquoi ?",
  ]),
  ...spc(1),
  corBox("Correction Exercice 4",[
    "Tour 1 : R1 [eau✓,lumière✓,terre✓] → plante_vivante",
    "Tour 2 : R2 [plante_vivante✓,fleurs✓] → plante_fleurie",
    "         R4 [plante_vivante✓,fruits✓] → plante_fruitière",
    "Tour 3 : R3 [plante_fleurie✓,odeur✓] → plante_parfumée",
    "         R5 [plante_fruitière✓,comestible✓] → plante_alimentaire",
    "Tour 4 : R6 [plante_parfumée✓, rare✗] → NON APPLICABLE → arrêt",
    "",
    "Base finale : eau, lumière, terre, fleurs, odeur, fruits, comestible,",
    "plante_vivante, plante_fleurie, plante_fruitière, plante_parfumée, plante_alimentaire",
    "R6 ne se déclenche pas : 'rare' est absent de la base de faits.",
  ]),
  br(),

  // PARTIE 5
  h1("PARTIE 5 — Le Chaînage Arrière"),
  defBox("Chaînage arrière — Définition",[
    "Mécanisme de raisonnement guidé par le but (objectif).",
    "On part d'une conclusion à vérifier et on remonte vers les faits.",
    "Direction : Objectif → Sous-objectifs → Faits",
  ]),
  ...spc(1),
  h2("5.2  Algorithme (récursif)"),
  codeBox([
    "PROUVER(objectif) :",
    "  SI objectif est dans la base de faits : RETOURNER vrai",
    "  SINON :",
    "    Chercher une règle R dont la conclusion = objectif",
    "    POUR chaque prémisse P de R :",
    "      SI PROUVER(P) = faux : RETOURNER faux",
    "    RETOURNER vrai",
  ]),
  ...spc(1),
  h2("5.3  Exemple — Tarte aux abricots"),
  codeBox([
    "But : tarte_aux_abricots",
    "Étape 1 : R4 (SI abricots ET pâte → tarte_aux_abricots)",
    "  Prémisse 'abricots' ? OUI ✓",
    "  Prémisse 'pâte' ? NON → sous-objectif : prouver 'pâte'",
    "Étape 2 : R1 (SI farine ET beurre ET oeufs ET sel → pâte)",
    "  farine✓ beurre✓ oeufs✓ sel✓ → pâte PROUVÉ ✓",
    "Retour : abricots✓ ET pâte✓ → tarte_aux_abricots PROUVÉ ✓",
  ]),
  ...spc(1),
  h2("5.4  Exemple formel (règles abstraites)"),
  codeBox([
    "R1:SI A ET B→C | R2:SI D→B | R3:SI E→A | R4:SI F→D",
    "Faits : E=vrai, F=vrai | Objectif : prouver C",
    "",
    "Prouver C → R1 nécessite A ET B",
    "  Prouver A → R3 : E=vrai✓ → A prouvé ✓",
    "  Prouver B → R2 nécessite D",
    "    Prouver D → R4 : F=vrai✓ → D prouvé ✓",
    "  → D✓ → B✓",
    "→ A✓ ET B✓ → C est PROUVÉ ✓",
  ]),
  ...spc(1),
  table2col("Chaînage AVANT","Chaînage ARRIÈRE",[
    ["Guidé par les faits","Guidé par le but (objectif)"],
    ["Faits → Conclusions","Objectif → Sous-objectifs → Faits"],
    ["Planification, interprétation","Diagnostic, prescription"],
    ["Peut générer des faits inutiles","Focalisé uniquement sur le but"],
  ]),
  ...spc(2),
  exoBox("Exercice 5 — Chaînage arrière",[
    "Règles : R1:SI P ET Q→S | R2:SI R→P | R3:SI T→Q | R4:SI U→R | R5:SI V→T",
    "Faits : U=vrai, V=vrai | Objectif : Prouver S",
    "",
    "1. Appliquez le chaînage arrière pas à pas.",
    "2. Dessinez l'arbre de déduction (sous-objectifs).",
    "3. S est-il prouvé ? Justifiez.",
  ]),
  ...spc(1),
  corBox("Correction Exercice 5",[
    "Prouver S → R1 (SI P ET Q → S)",
    "  Prouver P → R2 (SI R→P)",
    "    Prouver R → R4 (SI U→R) | U=vrai✓ → R✓ → P✓",
    "  Prouver Q → R3 (SI T→Q)",
    "    Prouver T → R5 (SI V→T) | V=vrai✓ → T✓ → Q✓",
    "→ P✓ ET Q✓ → S est PROUVÉ ✓",
    "",
    "Arbre de déduction :",
    "     S (objectif)",
    "    / \\",
    "   P   Q",
    "   |   |",
    "   R   T",
    "   |   |",
    "   U   V",
    " (vrai)(vrai)",
  ]),
  br(),

  // PARTIE 6
  h1("PARTIE 6 — Le Backtracking (Retour arrière)"),
  defBox("Backtracking — Définition",[
    "Mécanisme utilisé dans le chaînage arrière quand plusieurs chemins existent",
    "pour prouver un objectif. Si le chemin choisi échoue, on revient en arrière",
    "pour essayer un autre chemin disponible.",
  ]),
  ...spc(1),
  h2("6.2  Quand intervient-il ?"),
  p("Lorsque plusieurs règles ont la même conclusion. Si un chemin échoue (sous-objectif non prouvable), on revient et tente l'alternative."),
  codeBox([
    "Exemple simple :",
    "  R2 : SI D → B",
    "  R5 : SI G → B   (deux règles peuvent prouver B)",
    "",
    "Pour prouver B :",
    "  Tentative 1 : R2 → prouver D → si D échoue : BACKTRACK",
    "  Tentative 2 : R5 → prouver G",
  ]),
  ...spc(1),
  h2("6.3  Exemple complet"),
  codeBox([
    "R1:SI A ET B→G | R2:SI C→A | R3:SI D→A | R4:SI E→B | R5:SI F→B",
    "Faits : C=vrai, F=vrai  (D et E sont FAUX)",
    "Objectif : Prouver G",
    "",
    "Prouver G via R1 (SI A ET B → G) :",
    "  [Branche A] → R2 (SI C→A) | C=vrai✓ → A PROUVÉ ✓",
    "  [Branche B] → R4 (SI E→B) | E=FAUX✗ → ÉCHEC → BACKTRACK",
    "               → R5 (SI F→B) | F=vrai✓ → B PROUVÉ ✓",
    "→ A✓ ET B✓ → G est PROUVÉ ✓ (grâce au backtracking sur B)",
  ]),
  ...spc(2),
  exoBox("Exercice 6 — Backtracking",[
    "R1:SI X ET Y→Z | R2:SI A→X | R3:SI B→X | R4:SI C→Y | R5:SI D→Y",
    "Faits : B=vrai, C=vrai  (A et D sont FAUX)",
    "Objectif : Prouver Z",
    "",
    "1. Appliquez le chaînage arrière avec backtracking.",
    "2. Quel chemin échoue ? Sur quel fait ?",
    "3. Quel chemin alternatif est emprunté ?",
    "4. Z est-il finalement prouvé ?",
  ]),
  ...spc(1),
  corBox("Correction Exercice 6",[
    "Prouver Z via R1 (SI X ET Y → Z) :",
    "  [Prouver X] → R2 (SI A→X) | A=FAUX✗ → ÉCHEC → BACKTRACK",
    "               → R3 (SI B→X) | B=vrai✓ → X PROUVÉ ✓",
    "  [Prouver Y] → R4 (SI C→Y) | C=vrai✓ → Y PROUVÉ ✓",
    "→ X✓ ET Y✓ → Z est PROUVÉ ✓",
    "",
    "2. Chemin R2 échoue car A=FAUX.",
    "3. Chemin alternatif R3 emprunté (B=vrai).",
    "4. Oui, Z est prouvé grâce au backtracking sur X.",
  ]),
  br(),

  // PARTIE 7
  h1("PARTIE 7 — L'Arbre ET/OU"),
  defBox("Arbre ET/OU — Définition",[
    "Structure de représentation de raisonnement utilisée en IA.",
    "• Noeuds ET  : toutes les branches doivent être vraies",
    "• Noeuds OU  : une seule branche suffit à être vraie",
  ]),
  ...spc(1),
  h2("7.2  Correspondance avec les règles"),
  bul("La conclusion est un noeud parent."),
  bul("Les prémisses connectées par ET forment un noeud ET."),
  bul("Plusieurs règles pour la même conclusion forment un noeud OU."),
  codeBox([
    "R1 : SI A ET B → C   (noeud ET)",
    "R2 : SI D → C        (autre chemin pour C = noeud OU)",
    "",
    "Arbre ET/OU pour C :",
    "          C (objectif)",
    "         / \\",
    "       OU   OU",
    "       |     |",
    "   (A ET B)  D",
    "   /      \\",
    "  A        B",
    "→ C est vrai si (A=vrai ET B=vrai) OU D=vrai",
  ]),
  ...spc(1),
  h2("7.3  Exemple développé — Animaux"),
  codeBox([
    "R1 : SI mammifère ET carnivore         ALORS félin",
    "R2 : SI félin ET rayures               ALORS tigre",
    "R3 : SI félin ET crinière              ALORS lion",
    "R4 : SI mammifère ET herbivore ET longues_pattes  ALORS girafe",
    "",
    "Arbre ET/OU pour 'tigre' :",
    "          tigre",
    "            | (ET) R2",
    "         /      \\",
    "       félin   rayures",
    "         | (ET) R1",
    "       /        \\",
    "  mammifère   carnivore",
    "→ Pour prouver 'tigre' : mammifère ET carnivore ET rayures",
  ]),
  ...spc(2),
  exoBox("Exercice 7 — Arbre ET/OU",[
    "R1 : SI etudiant ET assidu            ALORS bon_etudiant",
    "R2 : SI bon_etudiant ET comprend_cours ALORS réussite",
    "R3 : SI travaille_seul                ALORS comprend_cours",
    "R4 : SI suit_tutoriel                 ALORS comprend_cours",
    "",
    "1. Construisez l'arbre ET/OU pour prouver 'réussite'.",
    "2. Quels sont les noeuds ET ? Les noeuds OU ?",
    "3. Avec : etudiant=vrai, assidu=vrai, suit_tutoriel=vrai, travaille_seul=FAUX",
    "   La réussite est-elle prouvée ? Montrez le chemin.",
  ]),
  ...spc(1),
  corBox("Correction Exercice 7",[
    "1. Arbre ET/OU pour 'réussite' :",
    "         réussite",
    "             | (ET) R2",
    "        /           \\",
    "  bon_etudiant   comprend_cours",
    "       | (ET) R1      | (OU)",
    "      / \\           /     \\",
    "  etud. assidu  travaille  suit_tut.",
    "                  _seul",
    "",
    "2. Noeuds ET  : réussite (R2), bon_etudiant (R1)",
    "   Noeuds OU  : comprend_cours (R3 ou R4)",
    "",
    "3. etudiant✓ ET assidu✓ → R1 → bon_etudiant✓",
    "   travaille_seul=FAUX → R3 échoue → BACKTRACK",
    "   suit_tutoriel=vrai✓ → R4 → comprend_cours✓",
    "   bon_etudiant✓ ET comprend_cours✓ → R2 → réussite PROUVÉE ✓",
  ]),
  br(),

  // PARTIE 8
  h1("PARTIE 8 — Avantages, Limites et Évolutions"),
  h2("8.1  Les avantages"),
  table2col("Avantage","Explication",[
    ["1. Capitaliser l'expertise","Préserver le savoir d'un expert qui peut partir à la retraite"],
    ["2. Aide à la décision","Fournir des recommandations fiables à des non-experts"],
    ["3. Disponibilité permanente","Disponible 24h/24, 7j/7, sans fatigue"],
    ["4. Gain de temps","Traiter automatiquement des milliers de cas instantanément"],
    ["5. Cohérence des décisions","Même résultat pour mêmes données, sans erreur d'inattention"],
    ["6. Formation","Outil pédagogique pour former de nouveaux experts"],
    ["7. Réduction des coûts","Diminuer le recours à des experts humains coûteux"],
  ]),
  ...spc(1),
  h2("8.2  Les limites"),
  bul("Champ de connaissances restreint : ne peut raisonner que dans son domaine précis."),
  bul("Maintenance difficile : la base de connaissances doit être mise à jour manuellement."),
  bul("Acquisition des connaissances : formaliser le savoir d'un expert est long et coûteux."),
  bul("Pas de bon sens : peut faire des erreurs absurdes hors de son domaine."),
  bul("Incapacité d'apprendre seul : ne peut pas améliorer sa base de règles sans intervention."),
  ...spc(1),
  h2("8.3  Systèmes experts hybrides (modernes)"),
  bul("Combinent les règles SI…ALORS classiques avec des algorithmes de Machine Learning."),
  bul("Le ML extrait automatiquement des règles à partir de grandes quantités de données."),
  noteBox("Les SE hybrides combinent la transparence des SE classiques avec la capacité d'apprentissage du ML."),
  ...spc(2),
  exoBox("Exercice 8 — Avantages et limites",[
    "1. Donnez 3 avantages d'un SE par rapport à un expert humain.",
    "2. Donnez 2 limites importantes et expliquez pourquoi elles sont problématiques.",
    "3. Qu'est-ce qu'un SE hybride ? Quel problème résout-il ?",
    "4. Citez un exemple où un SE classique serait insuffisant et un SE hybride plus adapté.",
  ]),
  ...spc(1),
  corBox("Correction Exercice 8",[
    "1. Trois avantages :",
    "   a) Disponibilité 24h/24 sans fatigue ni erreur d'inattention",
    "   b) Cohérence totale : même résultat pour mêmes données",
    "   c) Rapidité : traitement instantané de milliers de cas",
    "",
    "2. Deux limites :",
    "   a) Domaine restreint : hors de son domaine, le SE est inutile ou dangereux.",
    "   b) Maintenance : si le domaine évolue, un expert doit mettre à jour toutes les",
    "      règles manuellement — le SE peut devenir rapidement obsolète.",
    "",
    "3. SE hybride = règles SE classiques + algorithmes ML.",
    "   Résout l'acquisition des connaissances : le système apprend certaines règles",
    "   automatiquement depuis des données historiques.",
    "",
    "4. Détection de fraude bancaire :",
    "   SE classique : insuffisant, les fraudes évoluent constamment.",
    "   SE hybride : apprend automatiquement les nouveaux patterns de fraude.",
  ]),
  br(),

  // EXERCICE GÉNÉRAL
  h1("EXERCICE GÉNÉRAL — Synthèse Complète du Chapitre"),
  h2("Objectif"),
  p("Cet exercice couvre TOUTES les notions du chapitre : définition, composants, chaînage avant, chaînage arrière, backtracking et arbre ET/OU."),
  ...spc(1),
  exoBox("ÉNONCÉ — Système Expert Météorologique",[
    "Système expert pour recommander des activités selon la météo.",
    "",
    "Base de règles :",
    "  R1 : SI température > 25 ET ensoleillé          ALORS beau_temps",
    "  R2 : SI beau_temps ET mer_calme                 ALORS baignade_possible",
    "  R3 : SI beau_temps ET vent_fort                 ALORS kitesurf_possible",
    "  R4 : SI température < 10 ET nuageux             ALORS mauvais_temps",
    "  R5 : SI mauvais_temps ET pluie                  ALORS rester_intérieur",
    "  R6 : SI baignade_possible ET équipement_plongée  ALORS plongée_possible",
    "  R7 : SI kitesurf_possible ET certifié_kite       ALORS pratiquer_kitesurf",
    "  R8 : SI rester_intérieur ET musée_disponible     ALORS visiter_musée",
    "",
    "─── PARTIE A : Composants ──────────────────────────────────────",
    "  A1. Identifiez les 4 composants de ce système expert.",
    "  A2. Donnez 2 exemples de faits généraux pour la base de connaissances.",
    "",
    "─── PARTIE B : Chaînage avant ──────────────────────────────────",
    "  Cas 1 : température=28, ensoleillé=vrai, mer_calme=vrai,",
    "           vent_fort=vrai, équipement_plongée=vrai, certifié_kite=vrai",
    "  B1. Appliquez le chaînage avant étape par étape.",
    "  B2. Listez toutes les règles déclenchées dans l'ordre.",
    "  B3. Donnez la base de faits finale.",
    "  B4. Quelles activités sont recommandées ?",
    "",
    "─── PARTIE C : Chaînage arrière ────────────────────────────────",
    "  Cas 2 : température=28, ensoleillé=vrai, mer_calme=vrai, équipement_plongée=vrai",
    "  C1. Appliquez le chaînage arrière pour prouver 'plongée_possible'.",
    "  C2. Quels sont les sous-objectifs intermédiaires ?",
    "  C3. La plongée est-elle possible ? Justifiez.",
    "",
    "─── PARTIE D : Backtracking ────────────────────────────────────",
    "  Cas 3 : température=28, ensoleillé=vrai, vent_fort=vrai, certifié_kite=FAUX",
    "  D1. Essayez de prouver 'pratiquer_kitesurf'. Que se passe-t-il ?",
    "  D2. Y a-t-il un backtracking ? Sur quelle règle ?",
    "  D3. Quelle autre activité peut-on prouver avec ces faits ?",
    "",
    "─── PARTIE E : Avantages et limites ────────────────────────────",
    "  E1. Citez 2 avantages de ce SE météo par rapport à un guide touristique humain.",
    "  E2. Citez 1 limite et proposez comment un SE hybride pourrait l'améliorer.",
  ]),
  ...spc(2),
  corBox("CORRECTION — Partie A",[
    "A1. Les 4 composants :",
    "   1. Base de connaissances : règles R1 à R8 + faits généraux météo",
    "   2. Base de faits : données du cas (température, vent, etc.)",
    "   3. Moteur d'inférence : applique les règles pour déduire les activités",
    "   4. Interface utilisateur : saisie météo + affichage des conseils",
    "",
    "A2. Faits généraux :",
    "   - 'Le kitesurf nécessite une certification officielle'",
    "   - 'La plongée est dangereuse sans équipement adapté'",
  ]),
  ...spc(1),
  corBox("CORRECTION — Partie B : Chaînage avant",[
    "Faits initiaux : température=28, ensoleillé, mer_calme, vent_fort,",
    "                 équipement_plongée, certifié_kite",
    "",
    "Tour 1 : R1 [temp=28>25✓, ensoleillé✓] → beau_temps",
    "Tour 2 : R2 [beau_temps✓, mer_calme✓] → baignade_possible",
    "         R3 [beau_temps✓, vent_fort✓] → kitesurf_possible",
    "Tour 3 : R6 [baignade_possible✓, équipement_plongée✓] → plongée_possible",
    "         R7 [kitesurf_possible✓, certifié_kite✓] → pratiquer_kitesurf",
    "Tour 4 : Aucune règle applicable → arrêt",
    "",
    "Base finale : ...tous les faits initiaux + beau_temps, baignade_possible,",
    "              kitesurf_possible, plongée_possible, pratiquer_kitesurf",
    "Activités recommandées : plongée_possible ✓  +  pratiquer_kitesurf ✓",
  ]),
  ...spc(1),
  corBox("CORRECTION — Partie C : Chaînage arrière",[
    "Objectif : prouver 'plongée_possible'",
    "Faits : température=28, ensoleillé, mer_calme, équipement_plongée",
    "",
    "Étape 1 : R6 (SI baignade_possible ET équipement_plongée → plongée_possible)",
    "  équipement_plongée=vrai✓ | baignade_possible=? → sous-objectif",
    "Étape 2 : R2 (SI beau_temps ET mer_calme → baignade_possible)",
    "  mer_calme=vrai✓ | beau_temps=? → sous-objectif",
    "Étape 3 : R1 (SI temp>25 ET ensoleillé → beau_temps)",
    "  temp=28>25✓, ensoleillé✓ → beau_temps PROUVÉ ✓",
    "Retour : beau_temps✓ + mer_calme✓ → baignade_possible✓",
    "Retour : baignade_possible✓ + équipement_plongée✓ → plongée_possible PROUVÉE ✓",
    "Sous-objectifs : baignade_possible → beau_temps",
  ]),
  ...spc(1),
  corBox("CORRECTION — Partie D : Backtracking",[
    "Faits : température=28, ensoleillé, vent_fort, certifié_kite=FAUX",
    "",
    "D1. Prouver 'pratiquer_kitesurf' via R7 :",
    "    certifié_kite=FAUX✗ → ÉCHEC. Aucune règle alternative → IMPOSSIBLE.",
    "",
    "D2. Backtracking sur 'certifié_kite' : aucune règle ne peut le prouver.",
    "",
    "D3. Autre activité :",
    "    R1 : temp=28>25✓, ensoleillé✓ → beau_temps✓",
    "    R3 : beau_temps✓, vent_fort✓ → kitesurf_possible✓",
    "    → kitesurf_possible est prouvé (recommander des cours de kitesurf !)",
  ]),
  ...spc(1),
  corBox("CORRECTION — Partie E : Avantages et limites",[
    "E1. Deux avantages :",
    "   a) Disponibilité : réponse instantanée 24h/24 avec données météo en temps réel.",
    "   b) Cohérence : toujours la même décision pour mêmes conditions météo.",
    "",
    "E2. Limite : les règles sont fixes. Un nouveau sport (foilboard) nécessite",
    "    une mise à jour manuelle.",
    "    SE hybride : module ML analyse les retours utilisateurs et génère",
    "    automatiquement de nouvelles règles ou ajuste les seuils.",
  ]),
  ...spc(2),
  new Paragraph({
    children:[new TextRun({text:"Fin du document — Chapitre 2 : Systèmes Experts | GLSI2 — ISTIC 2025/2026",size:19,font:"Arial",color:"888888",italics:true})],
    alignment:AlignmentType.CENTER,
    border:{top:{style:BorderStyle.SINGLE,size:4,color:"CCCCCC"}},
    ...sp(200,80),
  }),

]; // end children

// Document
const doc = new Document({
  numbering:{
    config:[{
      reference:"bullets",
      levels:[{level:0,format:LevelFormat.BULLET,text:"•",alignment:AlignmentType.LEFT,
        style:{paragraph:{indent:{left:720,hanging:360}}}}]
    }]
  },
  styles:{
    default:{document:{run:{font:"Arial",size:22}}},
    paragraphStyles:[
      {id:"Heading1",name:"Heading 1",basedOn:"Normal",next:"Normal",quickFormat:true,
        run:{size:32,bold:true,font:"Arial",color:C.white},
        paragraph:{spacing:{before:320,after:160},outlineLevel:0}},
      {id:"Heading2",name:"Heading 2",basedOn:"Normal",next:"Normal",quickFormat:true,
        run:{size:26,bold:true,font:"Arial",color:C.primary},
        paragraph:{spacing:{before:220,after:100},outlineLevel:1}},
      {id:"Heading3",name:"Heading 3",basedOn:"Normal",next:"Normal",quickFormat:true,
        run:{size:23,bold:true,font:"Arial",color:C.primary},
        paragraph:{spacing:{before:180,after:80},outlineLevel:2}},
    ]
  },
  sections:[{
    properties:{
      page:{
        size:{width:12240,height:15840},
        margin:{top:1080,right:1080,bottom:1080,left:1080}
      }
    },
    children
  }]
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync('resume_systemes_experts.docx', buf);
  console.log('Document généré avec succès : resume_systemes_experts.docx');
}).catch(err => { console.error(err); process.exit(1); });
